name: Run tests for apps

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:12.2-alpine
        env:
          POSTGRES_USER: talana
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: talana_db
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      DATABASE_URL: postgres://talana:secret@localhost:5432/talana_db

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements/development.txt
    - name: Run tests
      run: |
        pytest --cov -v --tb=native
    - name: Linting
      run: |
        flake8 . --max-line-length=120 --exclude src/
